services:
  - type: web
    name: task
    env: docker
    plan: free
    branch: main
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        value: base64:hNxtdjAiuO3b+LYTD0/rRQWhl6/7rCAtaqUruoYq3J8=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
